#!/usr/bin/env bash
# Generated by server-init - restores the SSH configuration from before the change.
set -u
rm -f '/etc/ssh/sshd_config.d/00-server-init.conf'
rm -f '/etc/systemd/system/ssh.socket.d/server-init.conf'
cp -a '/var/lib/server-init/backup-1/files/etc/ssh/sshd_config' '/etc/ssh/sshd_config'
systemctl daemon-reload
systemctl reset-failed ssh.service ssh.socket 2>/dev/null
if systemctl is-enabled --quiet ssh.socket 2>/dev/null || systemctl is-active --quiet ssh.socket 2>/dev/null; then
    systemctl restart ssh.socket
fi
systemctl restart ssh.service 2>/dev/null || systemctl restart sshd.service
echo "$(date '+%F %T') server-init: SSH rollback executed" >>/var/log/server-init.log
echo "SSH configuration rolled back."
