package ssh

import (
	"context"
	"fmt"
	"slices"
	"strconv"
	"strings"

	"github.com/mimic890/server-init/internal/sys"
)

// Files written by the module.
const (
	DropIn         = "/etc/ssh/sshd_config.d/00-server-init.conf"
	SocketDropIn   = "/etc/systemd/system/ssh.socket.d/server-init.conf"
	BannerFile     = "/etc/ssh/server-init-banner"
	HostKey        = "/etc/ssh/ssh_host_ed25519_key"
	RollbackScript = "/var/lib/server-init/rollback-ssh.sh"
	PendingFile    = "/var/lib/server-init/ssh-pending.json"
	WatchdogUnit   = "server-init-ssh-watchdog"
	LogFile        = "/var/log/server-init.log"
)

// Files of the original ssh-setup.sh, taken over on migration.
var legacyFiles = []string{
	"/etc/ssh/sshd_config.d/00-ssh-setup.conf",
	"/etc/systemd/system/ssh.socket.d/ssh-setup.conf",
	"/etc/ssh/ssh-setup-banner",
}

// Modern algorithm lists; names the local OpenSSH does not know are dropped.
const (
	wantKex     = "sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org"
	wantCiphers = "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com"
	wantMACs    = "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com"
)

// Params is everything the sshd drop-in depends on.
type Params struct {
	Ports           []int
	RootLogin       string // prohibit-password | no
	MaxAuthTries    int
	LoginGraceTime  int
	ClientAlive     bool
	X11Forwarding   bool
	TCPForwarding   string
	AgentForwarding bool
	Banner          bool
	AllowUser       string // "" = no AllowUsers line
	Kex             string
	Ciphers         string
	MACs            string
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

// RenderConfig renders /etc/ssh/sshd_config.d/00-server-init.conf. The
// layout follows render_sshd_config of ssh-setup.sh.
func RenderConfig(p Params) string {
	var b strings.Builder
	b.WriteString("# Managed by server-init - re-run server-init instead of editing by hand.\n")
	b.WriteString("# Loaded first (00-) because sshd uses the FIRST value it sees for most options.\n\n")
	for _, port := range p.Ports {
		fmt.Fprintf(&b, "Port %d\n", port)
	}
	fmt.Fprintf(&b, `
# Authentication: keys only
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
AuthenticationMethods publickey
HostbasedAuthentication no
PermitUserEnvironment no
PermitRootLogin %s

# Brute-force limits
MaxAuthTries %d
LoginGraceTime %d
MaxStartups 10:30:60
`, p.RootLogin, p.MaxAuthTries, p.LoginGraceTime)
	if p.ClientAlive {
		b.WriteString("ClientAliveInterval 300\nClientAliveCountMax 2\n")
	}
	fmt.Fprintf(&b, `
# Forwarding
X11Forwarding %s
AllowTcpForwarding %s
AllowAgentForwarding %s

# Logging
LogLevel VERBOSE
`, yesNo(p.X11Forwarding), p.TCPForwarding, yesNo(p.AgentForwarding))
	if p.Banner {
		fmt.Fprintf(&b, "Banner %s\n", BannerFile)
	}
	if p.AllowUser != "" {
		fmt.Fprintf(&b, "\nAllowUsers %s\n", p.AllowUser)
	}
	fmt.Fprintf(&b, `
# Modern cryptography only (ed25519 keys)
HostKey %s
HostKeyAlgorithms ssh-ed25519
PubkeyAcceptedAlgorithms ssh-ed25519,sk-ssh-ed25519@openssh.com
KexAlgorithms %s
Ciphers %s
MACs %s
`, HostKey, p.Kex, p.Ciphers, p.MACs)
	return b.String()
}

// RenderSocket renders the ssh.socket drop-in (Ubuntu socket activation).
// The empty ListenStream= drops the addresses from ssh.socket and from the
// sshd-socket-generator.
func RenderSocket(ports []int) string {
	var b strings.Builder
	b.WriteString("# Managed by server-init\n[Socket]\nListenStream=\n")
	for _, p := range ports {
		fmt.Fprintf(&b, "ListenStream=%d\n", p)
	}
	return b.String()
}

// RestoreStep is one file operation of the rollback script.
type RestoreStep struct {
	Path   string
	Backup string // "" = delete Path
}

// RenderRollback renders the self-contained script that the watchdog timer
// runs. It must work even when server-init itself is gone.
func RenderRollback(steps []RestoreStep) string {
	var b strings.Builder
	b.WriteString(`#!/usr/bin/env bash
# Generated by server-init - restores the SSH configuration from before the change.
set -u
`)
	for _, s := range steps {
		if s.Backup == "" {
			fmt.Fprintf(&b, "rm -f %s\n", shq(s.Path))
		} else {
			fmt.Fprintf(&b, "cp -a %s %s\n", shq(s.Backup), shq(s.Path))
		}
	}
	fmt.Fprintf(&b, `systemctl daemon-reload
systemctl reset-failed ssh.service ssh.socket 2>/dev/null
if systemctl is-enabled --quiet ssh.socket 2>/dev/null || systemctl is-active --quiet ssh.socket 2>/dev/null; then
    systemctl restart ssh.socket
fi
systemctl restart ssh.service 2>/dev/null || systemctl restart sshd.service
echo "$(date '+%%F %%T') server-init: SSH rollback executed" >>%s
echo "SSH configuration rolled back."
`, LogFile)
	return b.String()
}

func shq(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }

// FilterAlgs keeps only the algorithms of list that `ssh -Q query` knows.
func FilterAlgs(ctx context.Context, s sys.System, query, list string) string {
	out, err := s.Query(ctx, "ssh", "-Q", query)
	if err != nil {
		return list
	}
	known := strings.Fields(out)
	var keep []string
	for _, a := range strings.Split(list, ",") {
		if slices.Contains(known, a) {
			keep = append(keep, a)
		}
	}
	if len(keep) == 0 {
		return list
	}
	return strings.Join(keep, ",")
}

// NeutralizePorts comments out active Port lines (sshd accumulates them).
func NeutralizePorts(content string) (string, bool) {
	lines := strings.SplitAfter(content, "\n")
	changed := false
	for i, l := range lines {
		t := strings.TrimLeft(l, " \t")
		f := strings.Fields(t)
		if len(f) >= 2 && strings.EqualFold(f[0], "Port") {
			if _, err := strconv.Atoi(f[1]); err == nil {
				lines[i] = "# disabled by server-init: " + l
				changed = true
			}
		}
	}
	return strings.Join(lines, ""), changed
}
