// Package ssh hardens OpenSSH. It is a port of ssh-setup.sh
// (github.com/Mimic890/ssh-setting-script) with the same behaviour:
// key-only login, custom port, modern crypto, one drop-in, and a two-phase
// port change guarded by a systemd watchdog that rolls back automatically.
package ssh

import (
	"context"
	"errors"
	"fmt"
	"path"
	"slices"
	"strings"

	"github.com/mimic890/server-init/internal/module"
	"github.com/mimic890/server-init/internal/modules/shared"
	"github.com/mimic890/server-init/internal/sys"
)

// Module is the ssh module.
type Module struct {
	form       *formState
	passphrase string

	// results for the report
	res result
}

type result struct {
	applied     bool
	confirmed   bool   // login confirmed (by the user or the automatic check)
	pending     bool   // old ports still open, waiting for `server-init ssh finalize`
	keyPath     string // generated private key
	keyDeleted  bool
	oldPorts    []int
	fw          firewall
	fwOpened    bool
	loginTarget string
}

// New returns the ssh module.
func New() *Module { return &Module{} }

func (*Module) ID() string   { return "ssh" }
func (*Module) Name() string { return "SSH hardening" }
func (*Module) Description() string {
	return "key-only login, custom port, modern crypto, safe two-phase port change"
}

// Prepare fills the port and the login user.
func (m *Module) Prepare(ctx context.Context, env *module.Env) error {
	a := &env.Answers.SSH
	if a.Port == 0 {
		a.Port = sys.RandomFreePort(ctx, env.Sys)
	}
	if a.User == "" {
		a.User = defaultUser(env)
	}
	return nil
}

// defaultUser is the admin the users module creates, else root.
func defaultUser(env *module.Env) string {
	u := env.Answers.Users
	if env.Selected("users") && u.CreateAdmin && u.Name != "" {
		return u.Name
	}
	return "root"
}

// settings are the answers resolved against the host.
type settings struct {
	port       int
	oldPorts   []int
	user       string
	home       string
	create     bool
	rootLogin  string
	params     Params
	pubKey     string // pasted key or the existing generated .pub
	genKeyPath string // generate mode: private key path
	generate   bool   // a new key pair must be generated
	fw         firewall
}

func (m *Module) resolve(ctx context.Context, env *module.Env) (settings, error) {
	a := &env.Answers.SSH
	if m.form != nil && !m.form.banner {
		a.Banner = ""
	}
	if a.User == "" {
		a.User = defaultUser(env)
	}
	var s settings
	if a.Port < 1 || a.Port > 65535 {
		return s, fmt.Errorf("invalid port %d", a.Port)
	}
	if !sys.UserNameRe.MatchString(a.User) {
		return s, fmt.Errorf("invalid user name %q", a.User)
	}
	switch a.TCPForwarding {
	case "no", "local", "yes":
	default:
		return s, fmt.Errorf("tcp_forwarding must be no, local or yes (got %q)", a.TCPForwarding)
	}
	s.port = a.Port
	s.oldPorts = env.Facts.SSHPorts
	if !slices.Contains(s.oldPorts, s.port) && sys.PortListening(ctx, env.Sys, s.port) {
		return s, fmt.Errorf("port %d is already in use by another program", s.port)
	}
	s.user = a.User
	if pw, ok := sys.LookupUser(ctx, env.Sys, a.User); ok {
		s.home = pw.Home
	} else {
		s.create = true
		s.home = "/home/" + a.User
	}
	s.rootLogin = "no"
	if a.User == "root" {
		s.rootLogin = "prohibit-password"
	}

	switch a.KeyMode {
	case "paste":
		k, err := shared.ParsePublicKey(a.PublicKey)
		if err != nil {
			return s, fmt.Errorf("ssh.public_key: %w", err)
		}
		a.PublicKey = k
		s.pubKey = k
	case "generate":
		s.genKeyPath = path.Join(s.home, ".ssh", "server-init_ed25519")
		if pub := strings.TrimSpace(sys.ReadString(env.Sys, s.genKeyPath+".pub")); pub != "" {
			s.pubKey = pub // generated by an earlier run
		} else {
			s.generate = true
			if a.Passphrase && m.passphrase == "" {
				return s, errors.New("a key passphrase can only be typed in the interactive mode; set ssh.passphrase: false")
			}
		}
	default:
		return s, fmt.Errorf("key_mode must be paste or generate (got %q)", a.KeyMode)
	}

	allow := ""
	if a.AllowOnly {
		allow = a.User
	}
	s.params = Params{
		Ports:           []int{s.port},
		RootLogin:       s.rootLogin,
		MaxAuthTries:    a.MaxAuthTries,
		LoginGraceTime:  a.LoginGraceTime,
		ClientAlive:     a.ClientAlive,
		X11Forwarding:   a.X11Forwarding,
		TCPForwarding:   a.TCPForwarding,
		AgentForwarding: a.AgentForwarding,
		Banner:          a.Banner != "",
		AllowUser:       allow,
		Kex:             FilterAlgs(ctx, env.Sys, "kex", wantKex),
		Ciphers:         FilterAlgs(ctx, env.Sys, "cipher", wantCiphers),
		MACs:            FilterAlgs(ctx, env.Sys, "mac", wantMACs),
	}
	s.fw = detectFirewall(ctx, env.Sys)
	return s, nil
}

func (m *Module) Check(ctx context.Context, env *module.Env) (module.Plan, error) {
	var p module.Plan
	s, err := m.resolve(ctx, env)
	if err != nil {
		return p, err
	}
	a := env.Answers.SSH
	if !sys.Has(env.Sys, "sshd") {
		p.Add(module.KindPackage, "openssh-server", "install openssh-server")
	}
	for _, f := range legacyFiles {
		p.PlanRemove(env.Sys, f, "remove "+f+" (taken over from ssh-setup.sh)")
	}
	others, _ := env.Sys.Glob("/etc/ssh/sshd_config.d/*.conf")
	for _, f := range append([]string{"/etc/ssh/sshd_config"}, others...) {
		if f == DropIn || slices.Contains(legacyFiles, f) {
			continue
		}
		if _, changed := NeutralizePorts(sys.ReadString(env.Sys, f)); changed {
			p.Add(module.KindFile, f, "comment out the active Port line in %s (backup kept)", f)
		}
	}
	if !sys.Exists(env.Sys, HostKey) {
		p.Add(module.KindCommand, HostKey, "generate the missing ed25519 host key")
	}
	if a.Banner != "" {
		p.PlanFile(env.Sys, BannerFile, a.Banner+"\n", 0o644, "login banner "+BannerFile)
	}
	if s.create && !usersModuleCreates(env, s.user) {
		p.Add(module.KindUser, s.user, "create user %s (no password, key login only)", s.user)
		if a.GrantSudo {
			p.Add(module.KindFile, shared.SudoersFile(s.user), "passwordless sudo for %s (%s)", s.user, shared.SudoersFile(s.user))
		}
	}
	ak := path.Join(s.home, ".ssh", "authorized_keys")
	switch {
	case s.generate:
		p.Add(module.KindCommand, s.genKeyPath, "generate an ed25519 key pair %s for %s", s.genKeyPath, s.user)
	case !shared.HasKey(sys.ReadString(env.Sys, ak), s.pubKey):
		p.Add(module.KindFile, ak, "add the public key to %s", ak)
	}

	cfg := RenderConfig(s.params)
	portChanged := !slices.Equal(s.oldPorts, []int{s.port})
	if p.PlanFile(env.Sys, DropIn, cfg, 0o644, "SSH settings "+DropIn) || portChanged {
		p.Risky(module.KindInfo, "port", "%s", portSummary(s))
		if env.Prompt.Interactive() {
			p.Add(module.KindInfo, "confirm", "you confirm the new login from a second terminal within %ds, otherwise everything is rolled back", int(ConfirmTimeout.Seconds()))
		} else {
			p.Add(module.KindInfo, "confirm", "the new login is tested automatically when the key was generated here; otherwise the old port stays open until `server-init ssh finalize`")
		}
	}
	if env.Facts.SSHSocket {
		p.PlanFile(env.Sys, SocketDropIn, RenderSocket([]int{s.port}), 0o644, "ssh.socket listens on the new port ("+SocketDropIn+")")
	}
	if portChanged {
		switch {
		case s.fw == fwUFW && env.Selected("ufw"):
			p.Add(module.KindCommand, "firewall", "ufw: allow %d/tcp before the switch (the ufw module sets the final rules)", s.port)
		case (s.fw == fwUFW || s.fw == fwFirewalld) && a.OpenFirewall:
			p.Add(module.KindCommand, "firewall", "%s: open %d/tcp", s.fw, s.port)
		case s.fw == fwUFW || s.fw == fwFirewalld:
			p.Note("%s is active and will NOT be opened for port %d: open it yourself or you will be locked out", s.fw, s.port)
		case s.fw == fwOther:
			p.Note("a firewall with a default DROP policy is active: open TCP %d yourself (custom rules are not edited)", s.port)
		}
	}
	if !p.Empty() && sys.Exists(env.Sys, PendingFile) {
		p.Note("a previous run is waiting for `server-init ssh finalize`; it is replaced by this run")
	}
	return p, nil
}

func portSummary(s settings) string {
	old := make([]string, len(s.oldPorts))
	for i, p := range s.oldPorts {
		old[i] = fmt.Sprint(p)
	}
	if slices.Equal(s.oldPorts, []int{s.port}) {
		return fmt.Sprintf("Port %d (unchanged), key-only login for %s", s.port, s.user)
	}
	return fmt.Sprintf("Port %s -> %d (the old port stays open until the new login is confirmed), key-only login for %s",
		strings.Join(old, ","), s.port, s.user)
}

// Report lists the SSH facts the user must remember.
func (m *Module) Report(env *module.Env) []module.ReportLine {
	if !m.res.applied {
		return nil
	}
	a := env.Answers.SSH
	lines := []module.ReportLine{
		{Label: "SSH port", Value: fmt.Sprint(a.Port)},
		{Label: "SSH user", Value: a.User},
		{Label: "Connect", Value: m.res.loginTarget},
	}
	if m.res.keyPath != "" {
		if m.res.keyDeleted {
			lines = append(lines, module.ReportLine{Label: "Public key", Value: m.res.keyPath + ".pub (private key deleted)"})
		} else {
			lines = append(lines,
				module.ReportLine{Label: "Private key", Value: m.res.keyPath + "  (copy it to your PC, then delete it here)", Warn: true},
				module.ReportLine{Label: "Public key", Value: m.res.keyPath + ".pub"})
		}
	}
	if m.res.pending {
		lines = append(lines, module.ReportLine{Label: "Old SSH port", Warn: true,
			Value: fmt.Sprintf("%v still open: log in on port %d, then run: server-init ssh finalize", m.res.oldPorts, a.Port)})
	}
	if (m.res.fw == fwUFW && !env.Selected("ufw") || m.res.fw == fwFirewalld) && m.res.fwOpened && !slices.Equal(m.res.oldPorts, []int{a.Port}) {
		lines = append(lines, module.ReportLine{Label: "Firewall", Warn: true,
			Value: fmt.Sprintf("old port(s) %v may still be open in %s: %s", m.res.oldPorts, m.res.fw, closeCmd(m.res.fw, m.res.oldPorts))})
	}
	if (m.res.fw == fwUFW || m.res.fw == fwFirewalld) && !m.res.fwOpened && !env.Selected("ufw") {
		lines = append(lines, module.ReportLine{Label: "Firewall", Warn: true, Value: fmt.Sprintf("port %d/tcp was NOT opened: %s", a.Port, openCmd(m.res.fw, a.Port))})
	}
	if m.res.fw == fwOther {
		lines = append(lines, module.ReportLine{Label: "Firewall", Warn: true, Value: fmt.Sprintf("open TCP %d in your own iptables/nftables rules", a.Port)})
	}
	lines = append(lines, module.ReportLine{Label: "Provider firewall", Warn: true,
		Value: fmt.Sprintf("if your hosting provider has a firewall / security group, open TCP %d there too", a.Port)})
	return lines
}

// usersModuleCreates reports whether the users module (which runs first)
// creates the login user.
func usersModuleCreates(env *module.Env, user string) bool {
	u := env.Answers.Users
	return env.Selected("users") && u.CreateAdmin && u.Name == user
}
